version: "3.7"

services:
  postgres:
    container_name: mall-postgres
    image: debezium/postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  elasticsearch:
    container_name: mall-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: mall-kibana
    image: docker.elastic.co/kibana/kibana:6.8.7
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logtash:
    container_name: mall-logtash
    image: docker.elastic.co/logstash/logstash:6.8.7
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
